### ISSUE TITLE
Link users from Dashboard/Hub/Docs to GraphQL w/ token

### ISSUE THREAD

**Issue by stevepeak** [storyscript/graphql#11]
Would be great to generate a link that redirect users to our [GraphiQL](http://api.storyscript.io/graphiql) with their auth token already in the headers. This way users do not have to manually find a token and insert it into a header. Also, these tokens can be short lived during their GraphQL session and expire shortly after.

**Comment by JeanBarriere** [comment]
This is implemented within our new stack, as we're using the same auth api for user authentication
